### ISSUE TITLE
大部分歌曲检索不到；检索条件可能过于严格？

### ISSUE THREAD

**Issue by publiclasss** [zhang435/Xiami_To_Spotify#11]
试图导入一个网易云音乐歌单，成功率82/225
仔细看了看曲目，发现很多Spotify绝对包含的歌也没能导入。例如
`[["Do You Bleed?","Hans ZimmerJunkie XL"],{"message":"Unable to find artirstHans ZimmerJunkie XL"}]`

可能是因为爬下来的信息不够准确（"Hans ZimmerJunkie XL"在原网页上为"Hans Zimmer/Junkie XL"），所以直接用它检索是搜不到什么东西的（。
另外网易/虾米上有很多标注为"Various Artists"的歌，同理也不能直接用爬虫结果检索（。

**Comment by zhang435** [comment]
小哥要不你优化下我的search ~~~~, 你发个PR我merge，我一直想优化来着，没啥子动力

**Comment by zhang435** [comment]
btw，我后来发现，在app端能搜到歌曲在API里面不一定能搜到，所以。。。我也很无奈啊
