### ISSUE TITLE
got application error

### ISSUE THREAD

**Issue by kid1412621** [zhang435/Xiami_To_Spotify#12]

**Comment by zhang435** [comment]
I am currently working on a new scawler to pass new type of sliding verfication that just appear on Xiami login page, it will be done in a week :)

**Comment by zhang435** [comment]
just fixed this issue

**Comment by kid1412621** [comment]
thank for your work, I wander if possible to import by playlist.
And Xiaomi just update their website, have to roll back to the older version.

**Comment by zhang435** [comment]
OMG, THEY UPDATE AGAIN... about add by playlist, there isn't an easy way to do so. But you can try to write a simple script, get all the playlist and use https://www.tunemymusic.com/ to import

**Comment by kid1412621** [comment]
Okay, but I guess I'm too lazy to do that.
B.t.w. My xiaomi list holds about 400 songs, but imported into Spotify only
merely 50%.

**Comment by zhang435** [comment]
which isn't surprising if the majority of your tracks are Chinese, where the Spotify Searching API did not do so well on searching Chinese tracks...

**Comment by kid1412621** [comment]
No, almost all post rock of foreign band.

**Comment by zhang435** [comment]
Can you send me your playlist URL?

**Comment by kid1412621** [comment]
> Can you send me your playlist URL?

https://www.xiami.com/space/lib-song/u/8109588/page/2?spm=a1z1s.6928797.1561534521.384.z1WNiT
