### ISSUE TITLE
对网易云喜欢的音乐链接无法识别

### ISSUE THREAD

**Issue by jiang-yuan** [zhang435/Xiami_To_Spotify#14]
我喜欢的音乐分享链接为:http://music.163.com/playlist?id=25233850&userid=33605117
你的example:https://music.163.com/#/playlist?id=123456
我改成https://music.163.com/#/playlist?id=25233850后成功识别

**Comment by zhang435** [comment]
dei,我觉得这不是个issue，我故意将url validation设置的严格是因为真的有很多用户提交过来的链接完全不对，只有这样才能保证提交之后每个用户链接都是有效的，小哥有兴趣可以改下我validation.js来把&userid这段给加上去，push 上来我 merge进去
