### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by anorangeJoe** [zhang435/Xiami_To_Spotify#15]
你好，我使用你的xiami to spotify导入，前两次都是导入到一半发生错误暂停，第三次我再尝试打开app时提示application error，无法使用了。
请问是否可以修复一下，非常感谢！

**Comment by anorangeJoe** [comment]
现在已可以使用，不好意思。

**Comment by zhang435** [comment]
?? 应该...  不会吧 。。。
