### ISSUE TITLE
Different error type

### ISSUE THREAD

**Issue by mogui520** [zhang435/Xiami_To_Spotify#20]
The page simply showed: unable to load page http://www.xiami.com/space/lib-song/u/5641982/page/1
While I'm submitted the right page (page 2).

**Comment by zhang435** [comment]
yeaa, the xiami recent change their url from `www` to `emumo`. There are some wiredness going on in this app. But to fix this issue, just comment out the validation part.

**Comment by zhang435** [comment]
I will try to deploy a new version this weekend

**Comment by zhang435** [comment]
I made deployment, seems like xiami fully deprecate www and use `emumo` instead, where the requests package seems not correctly redirect.. hmm to lazy to make fix
